version: '2.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:0.6.1
    ports:
      - "26002:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: "lenses:2181"

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:0.6.1
    environment:
      SERVER_HTTP_PORT: 9000

  lenses:
    image: landoop/kafka-lenses-dev
    ports:
      - "26001:3030"
      - "9092:9092"
      - "2181:2181"
      - "8081:8081"
    environment:
      ADV_HOST: 84.201.133.148
      EULA: "https://dl.lenses.stream/d/?id=8f4053d2-ddf7-457a-bac3-a42aa0a3a1c3"
