server.port: 8082

spring:
  profiles:
    active: dev, default
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: com.peterservice.rtco.commons.hibernate.h2.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true